### ISSUE TITLE
Retag latest release with v0.3.4

### ISSUE THREAD

**Issue by giuseongit** [madeindjs/Crystagiri#10]
The last version is tagged `0.3.4`. This causes shards to fail the fetch of this project as a described in #9.
As described in [here](https://github.com/crystal-lang/shards/issues/108) shards won't accept anymore tags that do not start with the `v`, so as long as the tag isn't fixed the only way to use crystagiri as a depencency is to target either `v0.3.2` or a branch such as `master`.

**Comment by madeindjs** [comment]
Thank you for report, I [updated the tag](https://github.com/madeindjs/Crystagiri/releases/tag/v0.3.4)
