### ISSUE TITLE
Parsing non HTML, XML documents

### ISSUE THREAD

**Issue by watzon** [madeindjs/Crystagiri#15]
Just wondering because there's no examples and I can't find anything in the source, how is this for parsing and exploring other XML documents such as RSS/Atom feeds? Should a new Document format be created specifically for navigating XML?

**Comment by madeindjs** [comment]
Internally, Crystagiri use [`XML#parse_html`](https://crystal-lang.org/api/0.28.0/XML.html#parse_html) so I don't think that you can't use Crystagiri but I suggest you to use the [`XML`](https://crystal-lang.org/api/0.28.0/XML.html) module.

**Comment by watzon** [comment]
Yeah I may do that. Thanks :blush:
