### ISSUE TITLE
Xpath example?

### ISSUE THREAD

**Issue by peyloride** [madeindjs/Crystagiri#4]
Hello thanks for your hard work. Is there any find by xpath example? I cant find.

Also how can I find subtags under a tag? For example there is six td tag under tr tag; I want to select them and read its content.

Thanks!

**Comment by gbetsan** [comment]
I prefer to use CSS selectors:

```
doc.css("tr td") do |td|
  ...
end
```

**Comment by madeindjs** [comment]
For xpath, you should directly use `XML::Node` in standard librairy. You can find some examples in [Crystal Documentation](https://crystal-lang.org/api/0.24.1/XML/Node.html#xpath%28path%2Cnamespaces%3Dnil%2Cvariables%3Dnil%29-instance-method).

About you CSS query, @grig191 's answer seem good .
