### ISSUE TITLE
Make blocks return

### ISSUE THREAD

**Issue by plainas** [madeindjs/Crystagiri#5]
Probably there are quick ways of doing this. But wouldn't it make more sense if the blocks returned so we can apply map(), filter() and such things afterwards?

**Comment by madeindjs** [comment]
You right. Would you try to implement it? :smile:

**Comment by plainas** [comment]
@madeindjs I can try yes.

**Comment by madeindjs** [comment]
Implemented in 710d12464500f51f61ae87ee2ecad045fe69ea22

**Comment by plainas** [comment]
Oh man. Sorry, I completely forgot this. Great to see this implemented anyway.
